# permissions for end users to edit policyendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: policyendpoints-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nodeagent
    app.kubernetes.io/part-of: nodeagent
    app.kubernetes.io/managed-by: kustomize
  name: policyendpoints-editor-role
rules:
- apiGroups:
  - policy.k8s.aws.nodeagent
  resources:
  - policyendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.k8s.aws.nodeagent
  resources:
  - policyendpoints/status
  verbs:
  - get
