---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - policy.k8s.aws.nodeagent
  resources:
  - policyendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.k8s.aws.nodeagent
  resources:
  - policyendpoints/finalizers
  verbs:
  - update
- apiGroups:
  - policy.k8s.aws.nodeagent
  resources:
  - policyendpoints/status
  verbs:
  - get
  - patch
  - update
