name: Manual E2E tests

on:
  workflow_dispatch:
    inputs:
      instance_type:
        type: choice
        description: Select Instance type (ARM - t4g.large, AMD - t3.large, GPU - p3.8xlarge) 
        options:
        - t3.large
        - t4g.large
        - p3.8xlarge

permissions:
  id-token: write
  contents: read

jobs:
  manual-e2e-conformance-tests:
    strategy:
      fail-fast: false
      matrix:
        ip-family: [ IPv4, IPv6 ]
        kubernetes-versions: ["1.25", "1.26", "1.27", "1.28"]
    if: github.repository == 'aws/aws-network-policy-agent'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v3
      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.OSS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 18000 # 5 hours
      - name: Run manual e2e conformance test
        env:
          RUN_CONFORMANCE_TESTS: true
          IP_FAMILY: ${{ matrix.ip-family }}
          INSTANCE_TYPE: ${{ github.event.inputs.instance_type }}
          K8S_VERSION: ${{ matrix.kubernetes-versions }}
          TEST_IMAGE_REGISTRY: ${{ secrets.TEST_IMAGE_REGISTRY }}
        run: |
          ./scripts/run-tests.sh
