name: Performance tests

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 9 * * 2" # every Tuesday

permissions:
  id-token: write
  contents: read

jobs:
  build-image:
    if: github.repository == 'aws/aws-network-policy-agent'
    runs-on: ubuntu-latest
    outputs:
      AWS_EKS_NODEAGENT_IMAGE: ${{steps.build-and-push-image.outputs.image_uri}}
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v3
      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.OSS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 3600 # 1 hour
      - name: Build and Push Network Policy Image
        id: build-and-push-image
        uses: ./.github/actions/build-and-push-image
        with:
          aws-region: us-west-2
  performance-tests:
    needs: build-image
    strategy:
      fail-fast: false
      matrix:
        ip-family: [ IPv4, IPv6 ]
        # kubernetes-versions: ["1.25", "1.26", "1.27"]
    if: github.repository == 'aws/aws-network-policy-agent'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v3
      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.OSS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 18000 # 5 hours
      - name: Run performance tests
        env:
          RUN_PERFORMANCE_TESTS: true
          NODES_CAPACITY: 3
          INSTANCE_TYPE: c5.xlarge
          IP_FAMILY: ${{ matrix.ip-family }}
          AWS_EKS_NODEAGENT_IMAGE: ${{ needs.build-image.outputs.AWS_EKS_NODEAGENT_IMAGE }}
        run: |
          ./scripts/run-tests.sh