name: Performance tests

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 9 * * 2" # every Tuesday

permissions:
  id-token: write
  contents: read

jobs:
  performance-tests:
    strategy:
      fail-fast: false
      matrix:
        ip-family: [ "IPv4", "IPv6"]
        # kubernetes-versions: ["1.25", "1.26", "1.27"]
    if: github.repository == 'aws/aws-network-policy-agent'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit in the PR
        uses: actions/checkout@v3
      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.OSS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-duration-seconds: 18000 # 5 hours
      - name: Run performance tests
        env:
          RUN_PERFORMANCE_TESTS: true
          KUBERNETES_VERSION: 1.27
          NODES_CAPACITY: 3
          INSTANCE_TYPE: c5.xlarge
          CNI_ADDON_VERSION: v1.14.0-eksbuild.3
          IP_FAMILY: ${{ matrix.ip-family }}
        run: |
          ./scripts/run-tests.sh
